version: "3.6"

services:
 test:
  build: ./test
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/mtzip/"
    - "./test/mod:/root/.minetest/worlds/world/worldmods/mtzip_test"
    - "./test/minetest.conf:/minetest.conf"
    - "./test/entrypoint.sh:/entrypoint.sh"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}