name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: mtzip
        mapgen: singlenode
        git_dependencies: |
          https://github.com/BuckarooBanzay/mtt
